# POSSEify plugin settings
posseify:
  twitter:
    max_length: 280
    url_length: 23
    link:
      min_hashtags: 1
      max_hashtags: 5
      template: "&#128279; @posse_content<br>\n@posse_url<br>\n<br>\n@posse_tags"
    post:
      min_hashtags: 3
      max_hashtags: 5
      template: "@posse_title\n\n@posse_url\n\n@posse_tags"

# Algolia
algolia:
  nodes_to_index: "p,li,figcaption,blockquote,th,td"
  files_to_exclude:
    - 404.html
    - index.html
    - search.html
    - offline.html
    - offline-fallback.html
    - about/mentions.html
    - tags/index.html
    - links/index.html
    - tools/*
