---
id: comment-2867815268
date: '2005-11-24 20:06:35 +0000'
updated: '2005-11-24 20:06:35 +0000'
post_id: "/2005/09/faut-il-utiliser-des-tags-composes-de-plusieurs-mots"
author:
  url:
  email: 
  image: no-avatar.png
  name: NiCoS
content: "<p>C'est pour me dire que je dois bosser que tu parles de sémantique
  ? ;-)</p>"