---
id: comment-2867806316
date: '2005-10-11 01:14:01 +0000'
updated: '2005-10-11 01:14:01 +0000'
post_id: "/2005/09/faut-il-utiliser-des-tags-composes-de-plusieurs-mots"
author:
  url:
  email: 
  image: no-avatar.png
  name: Onizuka
content: "<p>Personnellement, je pense qu'il faut utiliser les deux, je m'explique,
  le cas décrit par Monique, le Tag représente une catégorie
  d'un cas précis : &#034;Je suis partie sur l'<strong>Ile d'Oléron</strong>,
  pas sur une ile quelconque, par contre mon POST, mes photos, bref ma contribution
  peut intéresser les gens qui cherchent une info sur les ile en général
  dans ce cas, laisser le tag composé va limité la recherche.<br /><br />Blogmarks propose déjà
  un truc pas mal que sont les &#034;TAGS related&#034;.<br />A l'heure actuelle, personnellement, si j'hésite je les met tous.</p>
  <p>Mon voyage à Oléron donne donc : <br />Ile d'Oleron, Oléron, Ile, (et biere :p)</p> <p>Voila
  pour mon humble avis</p>"